# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ScateuCast
brand: ScateuCast
email: i@scateu.me
owner: Scateu
author: Scateu
copyright: Scateu
description: Scateu Podcast
baseurl: "" # the subpath of your site, e.g. /blog
category: Technology
permalink: "/podcast/:year/:month/:title/"

url: "https://podcast.scateu.me" # the base hostname & protocol for your site
default_thumb: "http://podcast.scateu.me/assets/img/kang.png"

# Build settings
markdown: kramdown

sass:
    sass_dir: assets/css

about: "Scateu的录音博客"
